### PR TITLE
Fix: Resolves Binary File not reading task.json

### PR DESCRIPTION
**Pull request by Realizedd**
Fixes binary file of our electron app not being able to read task,json by using relative path instead of absolute string file path.

### CODE REVIEW

**Review by Mashyuf — APPROVED** [review]
All looks good

**Review by katulevskiy — APPROVED** [review]
Changes are correct, LGTM, fixes the task.json bug as stated

**Review by katulevskiy — CHANGES_REQUESTED** [review]
bug is not resolved yet.

To recreate a bug:
delete task.json file in source/
launch the app with npm start
buttons will not be clickable, app not operational

**Comment by Realizedd** [comment]
Closing since I accidentally rebased instead of merging and kinda messed up commit history, check #130

**Pull request closed without merging**
