### PR TITLE
Hisham baobaid journal pt1

### PR DESCRIPTION
**Pull request by hbaobaid00**
I was able to create a markdown pop-up for the journal, however, I was unsuccessful in saving the data. I thought it would be good to have a text area as a placeholder for each date, but I still was unable to get it to save the data. Another thing I was thinking of was saving the data in a json file, but I am not that great at parsing so I was hoping someone could take over.

### CODE REVIEW

**Comment by hbaobaid00** [comment]
The issue with the css file interfering with some of the markdown syntax is still there as well (i.e. bullet points and lists)

**Review by Mashyuf — DISMISSED** [review]
The code is functioning and bug free. However, for the text area that shows up when hovered over, after inputting some text in that text area, and then open up the markdown overlay, the inputted text will not show up in the markdown side of the overlay.
electron_SFtdEEjSU2

**Comment by hbaobaid00** [comment]
The text area is not made to be edited but rather a place holder, however, I fixed it so that you can type in the text area and it will pop up in the journal. I am pretty sure there is a better way of trying to save the data but I am not sure.

**Review by Mashyuf — APPROVED** [review]
Everything looks good!

**Pull request merged**
