### PR TITLE
Major functionality overhaul: UI, Parser, Sorting

### PR DESCRIPTION
**Pull request by katulevskiy**
**Enhancements and Refactoring for Planner Application**

This PR introduces significant improvements and refactoring to enhance the functionality, UI consistency, and maintainability of the planner application. Key changes include:

- **UI Consistency**: Improved visual coherence across different pages with new stylesheets (`task-crud-style.css`, `taskbar-style.css`, `weekly-planner-style.css`).
- **Parser Fix**: Consolidated task data management into `json-parser.js`, fixing previous parsing issues and ensuring correct task handling.
- **Sorting and Filtering**: Added sorting functionality by importance and due date, improving task prioritization and management.
- **View Synchronization**: Ensured real-time synchronization between different views, providing a cohesive and up-to-date user experience.

Additional improvements include code refactoring for better modularity, comprehensive testing, and enhanced documentation for future maintainability. These updates significantly improve the application's overall performance and user experience.

### CODE REVIEW

**Review by Realizedd — APPROVED** [review]
Looks good

**Review by hbaobaid00 — APPROVED** [review]
looks good to me

**Comment by neelkanth-s** [comment]
Code Looks Good

**Review by andrewtran5222 — COMMENTED** [review]
Reviewed, code is valid

**Pull request merged**
