### PR TITLE
Journal now properly displays lists and header

### LINKED ISSUE #85: Add Journaling Functionality with Markdown Support
## Description
Implement journaling functionality in the journal view. The journal entries should support Markdown, use an API to render Markdown, and store each entry in separate Markdown files.

## Acceptance Criteria
- [x] Journal entries support Markdown.
- [x] API is used to render Markdown.
- [x] Journal entries are stored in separate Markdown files.

## Tasks
- [x] Implement Markdown support for journal entries.
- [x] Integrate API to render Markdown.
- [x] Implement functionality to store journal entries in separate Markdown files.

## Context
This feature will enhance the journaling experience by allowing users to format their entries using Markdown. Storing entries in separate files will help with organization and retrieval.

## Screenshots/Mockups
_Include any relevant screenshots or mockups if applicable._

## Testing Notes
- Verify that journal entries support Markdown formatting.
- Verify that the API correctly renders Markdown.
- Ensure journal entries are stored in separate Markdown files and can be retrieved correctly.

## Assignees
/assign @username

## Labels
/label enhancement, documentation

### PR DESCRIPTION
**Pull request by hbaobaid00**
Updated css and html so that markdown displays list and headers properly

### CODE REVIEW

**Comment by katulevskiy** [comment]
Please add saving markdown files into json or markdown, whatever makes more sense, after journal entry creation

**Review by katulevskiy — DISMISSED** [review]
Very good so far, rerequest review after the save functionality is implemented.

**Review by wsugiarto — APPROVED** [review]
looks good

**Pull request merged**
