### PR TITLE
Created json parser for both monthly and weekly view.

### PR DESCRIPTION
**Pull request by Mashyuf**
- Creates task.json if files are not found in the directory
- Reads task.json if file is found
- Populate the HTML file after parsing task.json

### CODE REVIEW

**Comment by katulevskiy** [comment]
monthly view bugs: 2 times same dates show up for next month

**Review by katulevskiy — CHANGES_REQUESTED** [review]
bug in monthly view + not working as intended

**Comment by Mashyuf** [comment]
All existing bugs have been fixed, the parser should be working as #61 stated.
Current issues:
- Editing background color will cause a bug, thus that line of code has been temporarily commentated out
- Need to add more comments and documentation

**Comment by wsugiarto** [comment]
Added:
JSON Parsers: New JSON parsers for both monthly and weekly views.
Custom Event Card Element: A custom HTML element <event-card> created for displaying event details.
Task Loading and Display: Functions to load tasks from a JSON file and display them in the backlog and calendar.
Edit and Delete Features: Integrated task editing and deletion with JSON parsing.
Improved:
HTML Structure: Refined HTML files to incorporate the new parsers and event cards.
JavaScript Functions: Enhanced with comments and error handling.
Potential Concerns:
Security: Usage of innerHTML in event-card for setting HTML content, which could introduce XSS vulnerabilities.
Performance: The recursive calls in planner.js and frequent DOM manipulations might affect performance

**Pull request merged**
